
public class Sym  {

    public static final int EOF    = 0;
    public static final int error  = 1;
    public static final int SEMICOLON = 2;
    public static final int PLUS   = 3;
    public static final int MINUS  = 4;
    public static final int MULT   = 5;
    public static final int EQ = 6;
    public static final int INTEGER = 7;
    public static final int PUBLIC = 8;
    public static final int CLASS = 9;
    public static final int IDENTIFIER = 10;
    public static final int INTEGER_LITERAL = 11;
    public static final int STRING_LITERAL = 12;
    public static final int FOR = 13;
    public static final int VOID = 14;
    public static final int READLINE = 15;
    public static final int READINTEGER = 16;
    public static final int INT = 17;
    public static final int RETURN = 18;
    public static final int INTERFACE = 19;
    public static final int EXTENDS = 20;
    public static final int ELSE = 21;
    public static final int WHILE = 22;
    public static final int BREAK = 23;
    public static final int DOUBLE = 24;
    public static final int IF = 25;
    public static final int BOOL = 26;
    public static final int NEW = 27;
    public static final int PRINT = 28;
    public static final int STRING = 29;
    public static final int IMPLEMENTS = 30;
    public static final int NEWARRAY = 31;
    public static final int NULL = 32;
    public static final int COM = 33;
    public static final int LESSEQ = 34;
    public static final int NOT = 35;
    public static final int AND = 36;
    public static final int DIV = 37;
    public static final int MOD = 38;
    public static final int LCBRAC = 39;
    public static final int LESS = 40;
    public static final int GREAT = 41;
    public static final int RBAC = 42;
    public static final int RPREN = 43;
    public static final int LPREN = 44;
    public static final int OR = 45;
    public static final int GREATEQ = 46;
    public static final int DIMS = 47;
    public static final int PER = 48;
    public static final int RCBRAC = 49;
    public static final int NOTEQ = 50;
    public static final int LBRAC = 51;
    public static final int EQEQ = 52;
    public static final int DOUBLE_LITERAL = 53;
    // And so on, for every terminal you use in MiniJava.jflex
    // define it here. 

    // In the next assignment, this file will be automatically
    // generated by CUP.
}