/* The following code was generated by JFlex 1.4.3 on 9/12/12 11:30 PM */

/* JFlex example: part of Java language lexer specification */

import java_cup.runtime.*;

/**
 * This class is a simple example lexer.
 */

public class Lexer extends Sym implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;
  private static final String ZZ_NL = System.getProperty("line.separator");

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int NESTED_COMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\6\1\3\1\2\1\0\1\3\1\1\16\6\4\0\1\3\1\62"+
    "\1\53\1\0\1\5\1\56\1\63\1\0\1\71\1\72\1\55\1\54"+
    "\1\66\1\15\1\13\1\4\1\7\11\10\1\0\1\65\1\57\1\61"+
    "\1\60\2\0\1\45\3\12\1\14\1\12\2\5\1\51\2\5\1\52"+
    "\1\5\1\44\1\5\1\47\1\5\1\50\5\5\1\11\2\5\1\67"+
    "\1\75\1\70\1\0\1\5\1\0\1\34\1\25\1\33\1\21\1\27"+
    "\1\35\1\32\1\42\1\20\1\5\1\43\1\26\1\37\1\22\1\17"+
    "\1\40\1\5\1\31\1\30\1\23\1\24\1\16\1\41\1\36\1\46"+
    "\1\5\1\73\1\64\1\74\1\0\41\6\2\0\4\5\4\0\1\5"+
    "\2\0\1\6\7\0\1\5\4\0\1\5\5\0\27\5\1\0\37\5"+
    "\1\0\u01ca\5\4\0\14\5\16\0\5\5\7\0\1\5\1\0\1\5"+
    "\21\0\160\6\5\5\1\0\2\5\2\0\4\5\10\0\1\5\1\0"+
    "\3\5\1\0\1\5\1\0\24\5\1\0\123\5\1\0\213\5\1\0"+
    "\5\6\2\0\236\5\11\0\46\5\2\0\1\5\7\0\47\5\11\0"+
    "\55\6\1\0\1\6\1\0\2\6\1\0\2\6\1\0\1\6\10\0"+
    "\33\5\5\0\3\5\15\0\4\6\7\0\1\5\4\0\13\6\5\0"+
    "\53\5\37\6\4\0\2\5\1\6\143\5\1\0\1\5\10\6\1\0"+
    "\6\6\2\5\2\6\1\0\4\6\2\5\12\6\3\5\2\0\1\5"+
    "\17\0\1\6\1\5\1\6\36\5\33\6\2\0\131\5\13\6\1\5"+
    "\16\0\12\6\41\5\11\6\2\5\4\0\1\5\5\0\26\5\4\6"+
    "\1\5\11\6\1\5\3\6\1\5\5\6\22\0\31\5\3\6\244\0"+
    "\4\6\66\5\3\6\1\5\22\6\1\5\7\6\12\5\2\6\2\0"+
    "\12\6\1\0\7\5\1\0\7\5\1\0\3\6\1\0\10\5\2\0"+
    "\2\5\2\0\26\5\1\0\7\5\1\0\1\5\3\0\4\5\2\0"+
    "\1\6\1\5\7\6\2\0\2\6\2\0\3\6\1\5\10\0\1\6"+
    "\4\0\2\5\1\0\3\5\2\6\2\0\12\6\4\5\7\0\1\5"+
    "\5\0\3\6\1\0\6\5\4\0\2\5\2\0\26\5\1\0\7\5"+
    "\1\0\2\5\1\0\2\5\1\0\2\5\2\0\1\6\1\0\5\6"+
    "\4\0\2\6\2\0\3\6\3\0\1\6\7\0\4\5\1\0\1\5"+
    "\7\0\14\6\3\5\1\6\13\0\3\6\1\0\11\5\1\0\3\5"+
    "\1\0\26\5\1\0\7\5\1\0\2\5\1\0\5\5\2\0\1\6"+
    "\1\5\10\6\1\0\3\6\1\0\3\6\2\0\1\5\17\0\2\5"+
    "\2\6\2\0\12\6\1\0\1\5\17\0\3\6\1\0\10\5\2\0"+
    "\2\5\2\0\26\5\1\0\7\5\1\0\2\5\1\0\5\5\2\0"+
    "\1\6\1\5\7\6\2\0\2\6\2\0\3\6\10\0\2\6\4\0"+
    "\2\5\1\0\3\5\2\6\2\0\12\6\1\0\1\5\20\0\1\6"+
    "\1\5\1\0\6\5\3\0\3\5\1\0\4\5\3\0\2\5\1\0"+
    "\1\5\1\0\2\5\3\0\2\5\3\0\3\5\3\0\14\5\4\0"+
    "\5\6\3\0\3\6\1\0\4\6\2\0\1\5\6\0\1\6\16\0"+
    "\12\6\11\0\1\5\7\0\3\6\1\0\10\5\1\0\3\5\1\0"+
    "\27\5\1\0\12\5\1\0\5\5\3\0\1\5\7\6\1\0\3\6"+
    "\1\0\4\6\7\0\2\6\1\0\2\5\6\0\2\5\2\6\2\0"+
    "\12\6\22\0\2\6\1\0\10\5\1\0\3\5\1\0\27\5\1\0"+
    "\12\5\1\0\5\5\2\0\1\6\1\5\7\6\1\0\3\6\1\0"+
    "\4\6\7\0\2\6\7\0\1\5\1\0\2\5\2\6\2\0\12\6"+
    "\1\0\2\5\17\0\2\6\1\0\10\5\1\0\3\5\1\0\51\5"+
    "\2\0\1\5\7\6\1\0\3\6\1\0\4\6\1\5\10\0\1\6"+
    "\10\0\2\5\2\6\2\0\12\6\12\0\6\5\2\0\2\6\1\0"+
    "\22\5\3\0\30\5\1\0\11\5\1\0\1\5\2\0\7\5\3\0"+
    "\1\6\4\0\6\6\1\0\1\6\1\0\10\6\22\0\2\6\15\0"+
    "\60\5\1\6\2\5\7\6\4\0\10\5\10\6\1\0\12\6\47\0"+
    "\2\5\1\0\1\5\2\0\2\5\1\0\1\5\2\0\1\5\6\0"+
    "\4\5\1\0\7\5\1\0\3\5\1\0\1\5\1\0\1\5\2\0"+
    "\2\5\1\0\4\5\1\6\2\5\6\6\1\0\2\6\1\5\2\0"+
    "\5\5\1\0\1\5\1\0\6\6\2\0\12\6\2\0\2\5\42\0"+
    "\1\5\27\0\2\6\6\0\12\6\13\0\1\6\1\0\1\6\1\0"+
    "\1\6\4\0\2\6\10\5\1\0\44\5\4\0\24\6\1\0\2\6"+
    "\5\5\13\6\1\0\44\6\11\0\1\6\71\0\53\5\24\6\1\5"+
    "\12\6\6\0\6\5\4\6\4\5\3\6\1\5\3\6\2\5\7\6"+
    "\3\5\4\6\15\5\14\6\1\5\17\6\2\0\46\5\12\0\53\5"+
    "\1\0\1\5\3\0\u0149\5\1\0\4\5\2\0\7\5\1\0\1\5"+
    "\1\0\4\5\2\0\51\5\1\0\4\5\2\0\41\5\1\0\4\5"+
    "\2\0\7\5\1\0\1\5\1\0\4\5\2\0\17\5\1\0\71\5"+
    "\1\0\4\5\2\0\103\5\2\0\3\6\40\0\20\5\20\0\125\5"+
    "\14\0\u026c\5\2\0\21\5\1\0\32\5\5\0\113\5\3\0\3\5"+
    "\17\0\15\5\1\0\4\5\3\6\13\0\22\5\3\6\13\0\22\5"+
    "\2\6\14\0\15\5\1\0\3\5\1\0\2\6\14\0\64\5\40\6"+
    "\3\0\1\5\3\0\2\5\1\6\2\0\12\6\41\0\3\6\2\0"+
    "\12\6\6\0\130\5\10\0\51\5\1\6\1\5\5\0\106\5\12\0"+
    "\35\5\3\0\14\6\4\0\14\6\12\0\12\6\36\5\2\0\5\5"+
    "\13\0\54\5\4\0\21\6\7\5\2\6\6\0\12\6\46\0\27\5"+
    "\5\6\4\0\65\5\12\6\1\0\35\6\2\0\13\6\6\0\12\6"+
    "\15\0\1\5\130\0\5\6\57\5\21\6\7\5\4\0\12\6\21\0"+
    "\11\6\14\0\3\6\36\5\12\6\3\0\2\5\12\6\6\0\46\5"+
    "\16\6\14\0\44\5\24\6\10\0\12\6\3\0\3\5\12\6\44\5"+
    "\122\0\3\6\1\0\25\6\4\5\1\6\4\5\1\6\15\0\300\5"+
    "\47\6\25\0\4\6\u0116\5\2\0\6\5\2\0\46\5\2\0\6\5"+
    "\2\0\10\5\1\0\1\5\1\0\1\5\1\0\1\5\1\0\37\5"+
    "\2\0\65\5\1\0\7\5\1\0\1\5\3\0\3\5\1\0\7\5"+
    "\3\0\4\5\2\0\6\5\4\0\15\5\5\0\3\5\1\0\7\5"+
    "\16\0\5\6\32\0\5\6\20\0\2\5\23\0\1\5\13\0\5\6"+
    "\5\0\6\6\1\0\1\5\15\0\1\5\20\0\15\5\3\0\32\5"+
    "\26\0\15\6\4\0\1\6\3\0\14\6\21\0\1\5\4\0\1\5"+
    "\2\0\12\5\1\0\1\5\3\0\5\5\6\0\1\5\1\0\1\5"+
    "\1\0\1\5\1\0\4\5\1\0\13\5\2\0\4\5\5\0\5\5"+
    "\4\0\1\5\21\0\51\5\u0a77\0\57\5\1\0\57\5\1\0\205\5"+
    "\6\0\4\5\3\6\16\0\46\5\12\0\66\5\11\0\1\5\17\0"+
    "\1\6\27\5\11\0\7\5\1\0\7\5\1\0\7\5\1\0\7\5"+
    "\1\0\7\5\1\0\7\5\1\0\7\5\1\0\7\5\1\0\40\6"+
    "\57\0\1\5\u01d5\0\3\5\31\0\11\5\6\6\1\0\5\5\2\0"+
    "\5\5\4\0\126\5\2\0\2\6\2\0\3\5\1\0\132\5\1\0"+
    "\4\5\5\0\51\5\3\0\136\5\21\0\33\5\65\0\20\5\u0200\0"+
    "\u19b6\5\112\0\u51cc\5\64\0\u048d\5\103\0\56\5\2\0\u010d\5\3\0"+
    "\20\5\12\6\2\5\24\0\57\5\1\6\14\0\2\6\1\0\31\5"+
    "\10\0\120\5\2\6\45\0\11\5\2\0\147\5\2\0\4\5\1\0"+
    "\2\5\16\0\12\5\120\0\10\5\1\6\3\5\1\6\4\5\1\6"+
    "\27\5\5\6\20\0\1\5\7\0\64\5\14\0\2\6\62\5\21\6"+
    "\13\0\12\6\6\0\22\6\6\5\3\0\1\5\4\0\12\6\34\5"+
    "\10\6\2\0\27\5\15\6\14\0\35\5\3\0\4\6\57\5\16\6"+
    "\16\0\1\5\12\6\46\0\51\5\16\6\11\0\3\5\1\6\10\5"+
    "\2\6\2\0\12\6\6\0\27\5\3\0\1\5\1\6\4\0\60\5"+
    "\1\6\1\5\3\6\2\5\2\6\5\5\2\6\1\5\1\6\1\5"+
    "\30\0\3\5\43\0\6\5\2\0\6\5\2\0\6\5\11\0\7\5"+
    "\1\0\7\5\221\0\43\5\10\6\1\0\2\6\2\0\12\6\6\0"+
    "\u2ba4\5\14\0\27\5\4\0\61\5\u2104\0\u012e\5\2\0\76\5\2\0"+
    "\152\5\46\0\7\5\14\0\5\5\5\0\1\5\1\6\12\5\1\0"+
    "\15\5\1\0\5\5\1\0\1\5\1\0\2\5\1\0\2\5\1\0"+
    "\154\5\41\0\u016b\5\22\0\100\5\2\0\66\5\50\0\15\5\3\0"+
    "\20\6\20\0\7\6\14\0\2\5\30\0\3\5\31\0\1\5\6\0"+
    "\5\5\1\0\207\5\2\0\1\6\4\0\1\5\13\0\12\6\7\0"+
    "\32\5\4\0\1\5\1\0\32\5\13\0\131\5\3\0\6\5\2\0"+
    "\6\5\2\0\6\5\2\0\3\5\3\0\2\5\3\0\2\5\22\0"+
    "\3\6\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\2\5\1\6\1\7"+
    "\17\4\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\2\1\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\3\33\1\0\1\34"+
    "\2\0\1\35\2\4\1\36\21\4\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\33\2\53\1\5\1\0\1\4\1\54\3\4"+
    "\1\55\10\4\1\56\4\4\1\35\1\0\1\57\3\4"+
    "\1\60\1\61\1\62\1\4\1\63\13\4\1\64\3\4"+
    "\1\65\1\66\1\4\1\67\4\4\1\70\1\4\1\71"+
    "\1\72\5\4\1\73\5\4\1\74\1\4\1\75\1\76"+
    "\2\4\1\77\1\4\1\100";

  private static int [] zzUnpackAction() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\272\0\370\0\272\0\u0136\0\u0174"+
    "\0\u01b2\0\u01f0\0\272\0\272\0\u022e\0\u026c\0\u02aa\0\u02e8"+
    "\0\u0326\0\u0364\0\u03a2\0\u03e0\0\u041e\0\u045c\0\u049a\0\u04d8"+
    "\0\u0516\0\u0554\0\u0592\0\272\0\272\0\272\0\272\0\u05d0"+
    "\0\u060e\0\u064c\0\u068a\0\u06c8\0\u0706\0\272\0\272\0\u0744"+
    "\0\272\0\272\0\272\0\272\0\272\0\u0782\0\272\0\u07c0"+
    "\0\u07fe\0\u083c\0\u087a\0\u08b8\0\272\0\u08f6\0\u0934\0\u0972"+
    "\0\u09b0\0\u09ee\0\u0174\0\u0a2c\0\u0a6a\0\u0aa8\0\u0ae6\0\u0b24"+
    "\0\u0b62\0\u0ba0\0\u0bde\0\u0c1c\0\u0c5a\0\u0c98\0\u0cd6\0\u0d14"+
    "\0\u0d52\0\u0d90\0\u0dce\0\u0e0c\0\272\0\272\0\272\0\272"+
    "\0\272\0\272\0\272\0\272\0\272\0\272\0\272\0\272"+
    "\0\u0e4a\0\u0e88\0\272\0\u0934\0\u0ec6\0\u0f04\0\u0f42\0\u0f80"+
    "\0\u0fbe\0\u0ffc\0\u0174\0\u103a\0\u1078\0\u10b6\0\u10f4\0\u1132"+
    "\0\u1170\0\u11ae\0\u11ec\0\u0174\0\u122a\0\u1268\0\u12a6\0\u12e4"+
    "\0\u1322\0\u1322\0\u0174\0\u1360\0\u139e\0\u13dc\0\u0174\0\u0174"+
    "\0\u0174\0\u141a\0\u0174\0\u1458\0\u1496\0\u14d4\0\u1512\0\u1550"+
    "\0\u158e\0\u15cc\0\u160a\0\u1648\0\u1686\0\u16c4\0\u0174\0\u1702"+
    "\0\u1740\0\u177e\0\u0174\0\u0174\0\u17bc\0\u0174\0\u17fa\0\u1838"+
    "\0\u1876\0\u18b4\0\u0174\0\u18f2\0\u0174\0\u0174\0\u1930\0\u196e"+
    "\0\u19ac\0\u19ea\0\u1a28\0\u0174\0\u1a66\0\u1aa4\0\u1ae2\0\u1b20"+
    "\0\u1b5e\0\u0174\0\u1b9c\0\u0174\0\u0174\0\u1bda\0\u1c18\0\u0174"+
    "\0\u1c56\0\u0174";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\7\1\10\1\4\1\11\1\12"+
    "\2\10\1\13\1\10\1\14\1\15\1\10\1\16\1\17"+
    "\1\20\1\21\1\10\1\22\1\10\1\23\1\24\1\25"+
    "\1\10\1\26\1\10\1\27\3\10\1\30\2\10\1\31"+
    "\2\10\1\32\1\33\2\10\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\4\1\56"+
    "\2\0\50\56\1\57\21\56\1\60\4\61\1\62\50\61"+
    "\1\63\20\61\100\0\1\6\77\0\1\64\50\0\1\65"+
    "\25\0\6\10\1\0\1\10\1\0\35\10\32\0\2\66"+
    "\1\67\1\0\1\70\22\0\1\67\46\0\2\12\2\0"+
    "\1\70\67\0\6\10\1\0\1\10\1\0\1\10\1\71"+
    "\33\10\30\0\6\10\1\0\1\10\1\0\4\10\1\72"+
    "\12\10\1\73\1\10\1\74\13\10\30\0\6\10\1\0"+
    "\1\10\1\0\1\10\1\75\33\10\30\0\6\10\1\0"+
    "\1\10\1\0\6\10\1\76\2\10\1\77\23\10\30\0"+
    "\6\10\1\0\1\10\1\0\13\10\1\100\21\10\30\0"+
    "\6\10\1\0\1\10\1\0\1\10\1\101\11\10\1\102"+
    "\21\10\30\0\6\10\1\0\1\10\1\0\10\10\1\103"+
    "\7\10\1\104\14\10\30\0\6\10\1\0\1\10\1\0"+
    "\5\10\1\105\27\10\30\0\6\10\1\0\1\10\1\0"+
    "\11\10\1\106\23\10\30\0\6\10\1\0\1\10\1\0"+
    "\10\10\1\107\24\10\30\0\6\10\1\0\1\10\1\0"+
    "\1\10\1\110\33\10\30\0\6\10\1\0\1\10\1\0"+
    "\24\10\1\111\10\10\30\0\6\10\1\0\1\10\1\0"+
    "\11\10\1\112\23\10\30\0\6\10\1\0\1\10\1\0"+
    "\13\10\1\113\21\10\30\0\6\10\1\0\1\10\1\0"+
    "\11\10\1\114\23\10\104\0\1\115\75\0\1\116\75\0"+
    "\1\117\75\0\1\120\77\0\1\121\76\0\1\122\101\0"+
    "\1\123\5\0\1\56\2\0\50\56\1\0\21\56\23\0"+
    "\1\124\1\125\5\0\1\126\21\0\1\127\22\0\4\61"+
    "\1\0\50\61\1\0\20\61\4\0\1\62\75\0\1\130"+
    "\50\0\1\131\20\0\1\64\1\132\1\133\73\64\7\0"+
    "\2\66\2\0\1\70\71\0\2\134\1\0\1\134\1\0"+
    "\1\134\4\0\1\134\3\0\1\134\1\0\1\134\3\0"+
    "\3\134\7\0\1\134\37\0\2\70\3\0\1\135\12\0"+
    "\1\135\53\0\6\10\1\0\1\10\1\0\2\10\1\136"+
    "\32\10\30\0\6\10\1\0\1\10\1\0\5\10\1\137"+
    "\27\10\30\0\6\10\1\0\1\10\1\0\22\10\1\140"+
    "\12\10\30\0\6\10\1\0\1\10\1\0\6\10\1\141"+
    "\26\10\30\0\6\10\1\0\1\10\1\0\10\10\1\142"+
    "\24\10\30\0\6\10\1\0\1\10\1\0\23\10\1\143"+
    "\11\10\30\0\6\10\1\0\1\10\1\0\6\10\1\144"+
    "\26\10\30\0\6\10\1\0\1\10\1\0\1\10\1\145"+
    "\33\10\30\0\6\10\1\0\1\10\1\0\11\10\1\146"+
    "\23\10\30\0\6\10\1\0\1\10\1\0\12\10\1\147"+
    "\22\10\30\0\6\10\1\0\1\10\1\0\5\10\1\150"+
    "\27\10\30\0\6\10\1\0\1\10\1\0\13\10\1\151"+
    "\21\10\30\0\6\10\1\0\1\10\1\0\5\10\1\152"+
    "\27\10\30\0\6\10\1\0\1\10\1\0\16\10\1\153"+
    "\16\10\30\0\6\10\1\0\1\10\1\0\13\10\1\154"+
    "\21\10\30\0\6\10\1\0\1\10\1\0\2\10\1\155"+
    "\32\10\30\0\6\10\1\0\1\10\1\0\23\10\1\156"+
    "\11\10\30\0\6\10\1\0\1\10\1\0\2\10\1\157"+
    "\32\10\30\0\6\10\1\0\1\10\1\0\16\10\1\160"+
    "\16\10\100\0\1\131\22\0\1\133\102\0\2\161\4\0"+
    "\1\162\36\0\1\162\26\0\6\10\1\0\1\10\1\0"+
    "\3\10\1\163\31\10\30\0\6\10\1\0\1\10\1\0"+
    "\11\10\1\164\23\10\30\0\6\10\1\0\1\10\1\0"+
    "\10\10\1\165\24\10\30\0\6\10\1\0\1\10\1\0"+
    "\7\10\1\166\25\10\30\0\6\10\1\0\1\10\1\0"+
    "\10\10\1\167\24\10\30\0\6\10\1\0\1\10\1\0"+
    "\11\10\1\170\23\10\30\0\6\10\1\0\1\10\1\0"+
    "\10\10\1\171\24\10\30\0\6\10\1\0\1\10\1\0"+
    "\16\10\1\172\16\10\30\0\6\10\1\0\1\10\1\0"+
    "\11\10\1\173\23\10\30\0\6\10\1\0\1\10\1\0"+
    "\11\10\1\174\23\10\30\0\6\10\1\0\1\10\1\0"+
    "\2\10\1\175\32\10\30\0\6\10\1\0\1\10\1\0"+
    "\6\10\1\176\26\10\30\0\6\10\1\0\1\10\1\0"+
    "\12\10\1\177\22\10\30\0\6\10\1\0\1\10\1\0"+
    "\10\10\1\200\24\10\30\0\6\10\1\0\1\10\1\0"+
    "\27\10\1\201\5\10\30\0\6\10\1\0\1\10\1\0"+
    "\4\10\1\202\30\10\30\0\6\10\1\0\1\10\1\0"+
    "\3\10\1\203\31\10\32\0\2\161\72\0\6\10\1\0"+
    "\1\10\1\0\13\10\1\204\21\10\30\0\6\10\1\0"+
    "\1\10\1\0\11\10\1\205\23\10\30\0\6\10\1\0"+
    "\1\10\1\0\10\10\1\206\24\10\30\0\6\10\1\0"+
    "\1\10\1\0\25\10\1\207\7\10\30\0\6\10\1\0"+
    "\1\10\1\0\4\10\1\210\30\10\30\0\6\10\1\0"+
    "\1\10\1\0\4\10\1\211\30\10\30\0\6\10\1\0"+
    "\1\10\1\0\13\10\1\212\21\10\30\0\6\10\1\0"+
    "\1\10\1\0\12\10\1\213\22\10\30\0\6\10\1\0"+
    "\1\10\1\0\11\10\1\214\23\10\30\0\6\10\1\0"+
    "\1\10\1\0\13\10\1\215\21\10\30\0\6\10\1\0"+
    "\1\10\1\0\5\10\1\216\27\10\30\0\6\10\1\0"+
    "\1\10\1\0\33\10\1\217\1\220\30\0\6\10\1\0"+
    "\1\10\1\0\17\10\1\221\15\10\30\0\6\10\1\0"+
    "\1\10\1\0\21\10\1\222\13\10\30\0\6\10\1\0"+
    "\1\10\1\0\11\10\1\223\23\10\30\0\6\10\1\0"+
    "\1\10\1\0\3\10\1\224\31\10\30\0\6\10\1\0"+
    "\1\10\1\0\14\10\1\225\20\10\30\0\6\10\1\0"+
    "\1\10\1\0\4\10\1\226\30\10\30\0\6\10\1\0"+
    "\1\10\1\0\13\10\1\227\21\10\30\0\6\10\1\0"+
    "\1\10\1\0\4\10\1\230\30\10\30\0\6\10\1\0"+
    "\1\10\1\0\2\10\1\231\32\10\30\0\6\10\1\0"+
    "\1\10\1\0\16\10\1\232\16\10\30\0\6\10\1\0"+
    "\1\10\1\0\11\10\1\233\23\10\30\0\6\10\1\0"+
    "\1\10\1\0\12\10\1\234\22\10\30\0\6\10\1\0"+
    "\1\10\1\0\16\10\1\235\16\10\30\0\6\10\1\0"+
    "\1\10\1\0\5\10\1\236\27\10\30\0\6\10\1\0"+
    "\1\10\1\0\4\10\1\237\30\10\30\0\6\10\1\0"+
    "\1\10\1\0\15\10\1\240\17\10\30\0\6\10\1\0"+
    "\1\10\1\0\4\10\1\241\30\10\30\0\6\10\1\0"+
    "\1\10\1\0\30\10\1\242\4\10\30\0\6\10\1\0"+
    "\1\10\1\0\11\10\1\243\23\10\30\0\6\10\1\0"+
    "\1\10\1\0\11\10\1\244\23\10\30\0\6\10\1\0"+
    "\1\10\1\0\11\10\1\245\23\10\30\0\6\10\1\0"+
    "\1\10\1\0\5\10\1\246\27\10\30\0\6\10\1\0"+
    "\1\10\1\0\14\10\1\247\20\10\30\0\6\10\1\0"+
    "\1\10\1\0\12\10\1\250\22\10\30\0\6\10\1\0"+
    "\1\10\1\0\11\10\1\251\23\10\30\0\6\10\1\0"+
    "\1\10\1\0\13\10\1\252\21\10\23\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7316];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\4\1\2\11\17\1\4\11"+
    "\6\1\2\11\1\1\5\11\1\1\1\11\4\1\1\0"+
    "\1\11\2\0\25\1\14\11\2\1\1\11\1\1\1\0"+
    "\24\1\1\0\70\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[170];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  int ANY = 0;
  StringBuffer string = new StringBuffer();
  Sym sym;

  private Symbol symbol(int type) {
    return new Symbol(type, yyline, yycolumn);
  }
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline, yycolumn, value);
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2244) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      /* your code goes here */
  yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 53: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [61] { return symbol(sym.CLASS); }");
          { return symbol(sym.CLASS);
          }
        case 65: break;
        case 1: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [149] { throw new Error(\"Illegal character <\"+ yytext()+\">\"); }");
          { throw new Error("Illegal character <"+ yytext()+">");
          }
        case 66: break;
        case 5: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [87] { return symbol(sym.INTEGER_LITERAL); }");
          { return symbol(sym.INTEGER_LITERAL);
          }
        case 67: break;
        case 61: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [76] { return symbol(sym.READLINE); }");
          { return symbol(sym.READLINE);
          }
        case 68: break;
        case 17: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [108] { return symbol(sym.COM); }");
          { return symbol(sym.COM);
          }
        case 69: break;
        case 43: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [120] { /* ignore comments*/ }");
          { /* ignore comments*/
          }
        case 70: break;
        case 29: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [86] { return symbol(sym.DOUBLE_LITERAL); }");
          { return symbol(sym.DOUBLE_LITERAL);
          }
        case 71: break;
        case 28: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [122] { yybegin(NESTED_COMMENT); }");
          { yybegin(NESTED_COMMENT);
          }
        case 72: break;
        case 64: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [75] { return symbol(sym.READINTEGER); }");
          { return symbol(sym.READINTEGER);
          }
        case 73: break;
        case 39: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [133] { string.append(\'\\t\'); }");
          { string.append('\t');
          }
        case 74: break;
        case 8: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [89] { string.setLength(0); yybegin(STRING); }");
          { string.setLength(0); yybegin(STRING);
          }
        case 75: break;
        case 44: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [57] { return symbol(sym.INT); }");
          { return symbol(sym.INT);
          }
        case 76: break;
        case 49: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [77] { return symbol(sym.BOOL, yytext()); }");
          { return symbol(sym.BOOL, yytext());
          }
        case 77: break;
        case 31: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [99] { return symbol(sym.LESSEQ); }");
          { return symbol(sym.LESSEQ);
          }
        case 78: break;
        case 15: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [106] { return symbol(sym.NOT); }");
          { return symbol(sym.NOT);
          }
        case 79: break;
        case 35: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [104] { return symbol(sym.AND); }");
          { return symbol(sym.AND);
          }
        case 80: break;
        case 3: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [95] { return symbol(sym.DIV); }");
          { return symbol(sym.DIV);
          }
        case 81: break;
        case 26: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [138] { string.append(\'\\\\\'); }");
          { string.append('\\');
          }
        case 82: break;
        case 58: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [70] { return symbol(sym.RETURN); }");
          { return symbol(sym.RETURN);
          }
        case 83: break;
        case 40: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [136] { string.append(\'\\r\'); }");
          { string.append('\r');
          }
        case 84: break;
        case 62: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [62] { return symbol(sym.INTERFACE); }");
          { return symbol(sym.INTERFACE);
          }
        case 85: break;
        case 42: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [141] { yybegin(YYINITIAL); }");
          { yybegin(YYINITIAL);
          }
        case 86: break;
        case 9: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [92] { return symbol(sym.PLUS); }");
          { return symbol(sym.PLUS);
          }
        case 87: break;
        case 11: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [96] { return symbol(sym.MOD); }");
          { return symbol(sym.MOD);
          }
        case 88: break;
        case 22: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [115] { return symbol(LCBRAC); }");
          { return symbol(LCBRAC);
          }
        case 89: break;
        case 59: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [64] { return symbol(sym.EXTENDS); }");
          { return symbol(sym.EXTENDS);
          }
        case 90: break;
        case 12: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [97] { return symbol(sym.LESS); }");
          { return symbol(sym.LESS);
          }
        case 91: break;
        case 25: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [129] { yybegin(YYINITIAL); "+ZZ_NL+"                                   return symbol(sym.STRING_LITERAL, "+ZZ_NL+"                                   string.toString()); }");
          { yybegin(YYINITIAL); 
                                   return symbol(sym.STRING_LITERAL, 
                                   string.toString());
          }
        case 92: break;
        case 47: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [56] { return symbol(sym.VOID); }");
          { return symbol(sym.VOID);
          }
        case 93: break;
        case 2: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [125] { /* ignore whitespace*/ }");
          { /* ignore whitespace*/
          }
        case 94: break;
        case 51: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [69] { return symbol(sym.ELSE); }");
          { return symbol(sym.ELSE);
          }
        case 95: break;
        case 41: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [137] { string.append(\'\\\"\'); }");
          { string.append('\"');
          }
        case 96: break;
        case 13: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [98] { return symbol(sym.GREAT); }");
          { return symbol(sym.GREAT);
          }
        case 97: break;
        case 10: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [94] { return symbol(sym.MULT); }");
          { return symbol(sym.MULT);
          }
        case 98: break;
        case 54: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [67] { return symbol(sym.WHILE); }");
          { return symbol(sym.WHILE);
          }
        case 99: break;
        case 56: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [58] { return symbol(sym.DOUBLE); }");
          { return symbol(sym.DOUBLE);
          }
        case 100: break;
        case 52: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [71] { return symbol(sym.BREAK); }");
          { return symbol(sym.BREAK);
          }
        case 101: break;
        case 30: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [68] { return symbol(sym.IF); }");
          { return symbol(sym.IF);
          }
        case 102: break;
        case 19: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [112] { return symbol(RBAC); }");
          { return symbol(RBAC);
          }
        case 103: break;
        case 21: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [114] { return symbol(RPREN); }");
          { return symbol(RPREN);
          }
        case 104: break;
        case 20: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [113] { return symbol(LPREN); }");
          { return symbol(LPREN);
          }
        case 105: break;
        case 36: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [105] { return symbol(sym.OR); }");
          { return symbol(sym.OR);
          }
        case 106: break;
        case 14: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [102] { return symbol(sym.EQ); }");
          { return symbol(sym.EQ);
          }
        case 107: break;
        case 32: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [100] { return symbol(sym.GREATEQ); }");
          { return symbol(sym.GREATEQ);
          }
        case 108: break;
        case 50: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [59] { return symbol(sym.BOOL); }");
          { return symbol(sym.BOOL);
          }
        case 109: break;
        case 46: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [66] { return symbol(sym.FOR); }");
          { return symbol(sym.FOR);
          }
        case 110: break;
        case 16: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [107] { return symbol(sym.SEMICOLON); }");
          { return symbol(sym.SEMICOLON);
          }
        case 111: break;
        case 38: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [134] { string.append(\'\\n\'); }");
          { string.append('\n');
          }
        case 112: break;
        case 37: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [110] { return symbol(sym.DIMS); }");
          { return symbol(sym.DIMS);
          }
        case 113: break;
        case 7: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [93] { return symbol(sym.MINUS); }");
          { return symbol(sym.MINUS);
          }
        case 114: break;
        case 45: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [72] { return symbol(sym.NEW); }");
          { return symbol(sym.NEW);
          }
        case 115: break;
        case 55: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [74] { return symbol(sym.PRINT); }");
          { return symbol(sym.PRINT);
          }
        case 116: break;
        case 6: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [109] { return symbol(sym.PER); }");
          { return symbol(sym.PER);
          }
        case 117: break;
        case 23: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [116] { return symbol(RCBRAC); }");
          { return symbol(RCBRAC);
          }
        case 118: break;
        case 57: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [60] { return symbol(sym.STRING); }");
          { return symbol(sym.STRING);
          }
        case 119: break;
        case 63: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [65] { return symbol(sym.IMPLEMENTS); }");
          { return symbol(sym.IMPLEMENTS);
          }
        case 120: break;
        case 34: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [103] { return symbol(sym.NOTEQ); }");
          { return symbol(sym.NOTEQ);
          }
        case 121: break;
        case 60: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [73] { return symbol(sym.NEWARRAY); }");
          { return symbol(sym.NEWARRAY);
          }
        case 122: break;
        case 4: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [81] { string.setLength(0);"+ZZ_NL+"  \t\t\t\t\t\t\t\t\tstring.append(yytext());"+ZZ_NL+"  \t\t\t\t\t\t\t\t\treturn symbol(sym.IDENTIFIER, string.toString()); }");
          { string.setLength(0);
  									string.append(yytext());
  									return symbol(sym.IDENTIFIER, string.toString());
          }
        case 123: break;
        case 24: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [132] { string.append( yytext() ); }");
          { string.append( yytext() );
          }
        case 124: break;
        case 18: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [111] { return symbol(LBRAC); }");
          { return symbol(LBRAC);
          }
        case 125: break;
        case 48: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [63] { return symbol(sym.NULL); }");
          { return symbol(sym.NULL);
          }
        case 126: break;
        case 33: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [101] { return symbol(sym.EQEQ); }");
          { return symbol(sym.EQEQ);
          }
        case 127: break;
        case 27: 
          System.out.println("line: "+(yyline+1)+" "+"col: "+(yycolumn+1)+" "+"match: --"+yytext()+"--");
          System.out.println("action [142] {  }");
          { 
          }
        case 128: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(Sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          scanner = new Lexer( new java.io.FileReader(argv[i]) );
          do {
            System.out.println(scanner.next_token());
          } while (!scanner.zzAtEOF);

        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
